import { z } from "zod";
import { MissingInfoResolution } from "../dto.js";

/**
 * `course-requirements` — the contract recorded after the interview (FR-012).
 * Generated by the `emit_course_requirements` tool; validated before persist.
 */
export const MissingInfoItem = z.object({
  item: z.string().min(1),
  resolution: MissingInfoResolution,
  detail: z.string().min(1),
});
export type MissingInfoItem = z.infer<typeof MissingInfoItem>;

export const CourseRequirementsContent = z.object({
  /** Datos generales: audience, sessions, durations, modality, etc. */
  general_data: z.string().min(1),
  /** Note on any source material provided (or that none was). */
  source_material_note: z.string().min(1),
  /** Devices, connectivity, allowed/prohibited platforms. */
  available_technology: z.string().min(1),
  /** Language, frameworks applied, evaluation approach, inclusion stance. */
  pedagogical_criteria: z.string().min(1),
  /** Assumptions, what will NOT be generated, output format. */
  constraints_decisions: z.string().min(1),
  /** Every unresolved item with how it was resolved (SC-002). */
  missing_info: z.array(MissingInfoItem),
});
export type CourseRequirementsContent = z.infer<typeof CourseRequirementsContent>;
