import { z } from "zod";
import { BloomLevel } from "../dto.js";

/** A learning objective: observable verb + Bloom level (FR-014). */
export const Objective = z.object({
  statement: z.string().min(1),
  bloom_level: BloomLevel,
});
export type Objective = z.infer<typeof Objective>;

/** A planned session (a "class") inside the main-plan (data-model: embedded). */
export const PlannedSession = z.object({
  ordinal: z.number().int().positive(),
  title: z.string().min(1),
  central_content: z.string().min(1),
  session_type: z.string().min(1),
  objectives: z.array(Objective).min(1),
  notes: z.string().optional(),
});
export type PlannedSession = z.infer<typeof PlannedSession>;

/** A time block within a session type. */
export const TimeBlock = z.object({
  name: z.string().min(1),
  activity: z.string().min(1),
  minutes: z.number().int().positive(),
});

/** Time distribution for one session type; total must equal the duration. */
export const SessionTypeDistribution = z.object({
  session_type: z.string().min(1),
  total_minutes: z.number().int().positive(),
  blocks: z.array(TimeBlock).min(1),
});
export type SessionTypeDistribution = z.infer<typeof SessionTypeDistribution>;

/**
 * `main-plan` — the pedagogical blueprint (FR-013). Generated by `emit_main_plan`.
 * The time-distribution sum rule (FR-015 / SC-003) is enforced via `.superRefine`.
 */
export const MainPlanContent = z
  .object({
    description: z.string().min(1),
    narrative_thread: z.string().min(1),
    sessions: z.array(PlannedSession).min(1),
    time_distribution: z.array(SessionTypeDistribution).min(1),
    difficulty_progression: z.string().min(1),
    accessibility_plan: z.string().min(1),
    technology: z.string().min(1),
    planned_files: z.array(z.string().min(1)).min(1),
  })
  .superRefine((plan, ctx) => {
    plan.time_distribution.forEach((dist, i) => {
      const sum = dist.blocks.reduce((acc, b) => acc + b.minutes, 0);
      if (sum !== dist.total_minutes) {
        ctx.addIssue({
          code: z.ZodIssueCode.custom,
          path: ["time_distribution", i, "blocks"],
          message: `Time blocks for "${dist.session_type}" sum to ${sum} but total_minutes is ${dist.total_minutes} (FR-015).`,
        });
      }
    });
  });
export type MainPlanContent = z.infer<typeof MainPlanContent>;
